name: Build & Deploy Lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Lambda function
        run: |
          GOOS=linux GOARCH=amd64 go build -o journal-reminder
          go mod vendor
          mkdir deployment
          cp journal-reminder deployment/
          cp -r vendor deployment/
          cd deployment
          zip -r ../dist.zip *

      - name: Upload ZIP file to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download ZIP file from artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist.zip

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name journal-reminder \
            --zip-file fileb://dist.zip