name: Build & Deploy Lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Lambda function
        run: |
          GOOS=linux GOARCH=amd64 go build -o journal-reminder cmd/aws-lambda/main.go
          chmod +x journal-reminder
          go mod vendor
          mkdir deployment
          cp journal-reminder deployment/
          cp -r vendor deployment/
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > deployment/credentials.json
          cd deployment
          zip -r ../dist.zip *

      - name: Upload ZIP file to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: List artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: artifacts

      - name: Debug
        run: |
          echo "=== Artifacts ==="
          ls -laR artifacts
          echo "=== Artifacts/deployment ==="
          ls -laR artifacts/deployment

      - name: Download ZIP file from artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist.zip

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda function
        run: |
          cd artifacts
          aws lambda update-function-code \
            --function-name journal-reminder \
            --zip-file fileb://dist.zip