name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  AWS_LAMBDA_FUNCTION_NAME: journal-reminder
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # include the build job
      - name: Build
        uses: ./.github/workflows/build.yml
  deploy:
    needs: build # make deploy depend on build job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: ./.github/workflows/deploy.yml